### ISSUE TITLE
The user can sign-up/register for memberships

### ISSUE THREAD

**Issue by tanttran** [tanttran/Pet#1]

**Comment by octttran** [comment]
![draft of sign-up page](https://occs.mybalsamiq.com/projects/occs-three/pet-register)

**Comment by octttran** [comment]
![Sign-up draft](https://occs.mybalsamiq.com/projects/occs-three/pet-register.jpeg?version=3&etag=F4IctaMyBppt2N3qLHk6gIpPzwMwDfxs)
